import { PropsWithChildren } from 'react';
import { Footer } from '@/components/footer/Footer';
import { Header } from '@/components/header/Header';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};
const UserLayout = ({ children }: PropsWithChildren) => {
  return (
    <div className="max-lg:w-full h-screen flex flex-col mx-10">
        <Header/>
      <div className="flex-1">{children}</div>
      <Footer />
    </div>
  );
};
export default UserLayout;
